export const ADD_TODO = 'ADD_TODO';
export const TOGGLE_TODO_COMPLETE = 'TOGGLE_TODO_COMPLETE';
export const REMOVE_TODO_ITEM = 'REMOVE_TODO_ITEM';
export const CREATE_TODO = 'CREATE_TODO';
export const SET_LOADING_STATE = 'SET_LOADING_STATE';
